name: "lint changes files"
on: push

jobs:
  luacheck-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Luacheck Linter
        uses: judaew/luacheck-action@v0.2.2
